## https://taskfile.dev
###---------------------

version: '3'

tasks:
    lint:
        cmds:
            - golangci-lint run

    test:
        cmds:
            - go test -cover -v ./...

    default:
        cmds:
            - task: lint
            - task: test

